### ISSUE TITLE
[aws][ci] Install SSM agent for all distros in EC2 test and enable patch by default

### ISSUE THREAD

**Issue by pingleig** [aws-observability/aws-otel-collector-test-framework#253]
Currently only AMI from Amazon ships with SSM agent by default, which is required for patching instances (e.g. #216 ).

## TODO

- [x] list AMIs that does not come with SSM #254 
- [x] list AMIs that does not come with python (e.g. RHEL 8)
- [x] use user data to install SSM agent
- [x] set patch to true when running in github action aws-observability/aws-otel-collector#431

**Comment by pingleig** [comment]
Done, though short term tests didn't enable patch because the CI would be too slow with it.
